name: Go Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'src/go.mod'
        cache-dependency-path: 'src/go.sum'

    - name: Download dependencies
      run: |
        cd src
        go mod download

    - name: Build
      run: |
        cd src
        go build -v ./cmd/main
